## Part 1: Preprocessing

In [52]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers, Input
from tensorflow.keras.layers import Dense

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [53]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [54]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[["Attrition", "Department"]]

# Preview the target DataFrame
y_df.head()


Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [55]:
# Create a list of at least 10 column names to use as X data
x_cols = [
    "Age",
    "DistanceFromHome",
    "Education",
    "JobSatisfaction",
    "WorkLifeBalance",
    "JobLevel",
    "NumCompaniesWorked",
    "TrainingTimesLastYear",
    "YearsAtCompany",
    "EnvironmentSatisfaction"
]

# Create X_df using your selected columns
X_df = attrition_df[x_cols]

# Show the data types for X_df
X_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1470 non-null   int64
 1   DistanceFromHome         1470 non-null   int64
 2   Education                1470 non-null   int64
 3   JobSatisfaction          1470 non-null   int64
 4   WorkLifeBalance          1470 non-null   int64
 5   JobLevel                 1470 non-null   int64
 6   NumCompaniesWorked       1470 non-null   int64
 7   TrainingTimesLastYear    1470 non-null   int64
 8   YearsAtCompany           1470 non-null   int64
 9   EnvironmentSatisfaction  1470 non-null   int64
dtypes: int64(10)
memory usage: 115.0 KB


In [56]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X_df, y_df, test_size=0.2, random_state=42
)

# Confirm shapes
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (1176, 10)
X_test shape: (294, 10)
y_train shape: (1176, 2)
y_test shape: (294, 2)


In [22]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary


In [57]:
#Check data types
X_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1470 non-null   int64
 1   DistanceFromHome         1470 non-null   int64
 2   Education                1470 non-null   int64
 3   JobSatisfaction          1470 non-null   int64
 4   WorkLifeBalance          1470 non-null   int64
 5   JobLevel                 1470 non-null   int64
 6   NumCompaniesWorked       1470 non-null   int64
 7   TrainingTimesLastYear    1470 non-null   int64
 8   YearsAtCompany           1470 non-null   int64
 9   EnvironmentSatisfaction  1470 non-null   int64
dtypes: int64(10)
memory usage: 115.0 KB


All data in X_df are int64.  No need to convert.

In [58]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [59]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
dept_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
dept_encoder.fit(y_train[["Department"]])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_dept = dept_encoder.transform(y_train[["Department"]])
y_test_dept = dept_encoder.transform(y_test[["Department"]])
print(y_train_dept)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [60]:
# Get the number of unique department categories
num_dept_classes = len(dept_encoder.categories_[0])
print(f"Number of department classes: {num_dept_classes}")


Number of department classes: 3


In [61]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
attrition_encoder.fit(y_train[["Attrition"]])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_attr = attrition_encoder.transform(y_train[["Attrition"]])
y_test_attr = attrition_encoder.transform(y_test[["Attrition"]])
print(y_train_attr)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]


In [62]:
# Check number of unique classes in Attrition
num_attrition_classes = len(attrition_encoder.categories_[0])
print(f"Number of attrition classes: {num_attrition_classes}")

Number of attrition classes: 2


## Part 2: Create, Compile, and Train the Model

In [63]:
# Find the number of columns in the X training data.
input_shape = X_train_scaled.shape[1]
print(f"Number of input features: {input_shape}")

# Create the input layer
input_layer = Input(shape=(10,), name="input")

# Create at least two shared layers
shared1 = Dense(64, activation="relu", name="shared1")(input_layer)
shared2 = Dense(128, activation="relu", name="shared2")(shared1)

Number of input features: 10


In [70]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
department_hidden = Dense(32, activation="relu", name="department_hidden")(shared2)

# Create the output layer
attrition_output = Dense(2, activation="softmax", name="attrition_output")(attrition_hidden)

In [71]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden = Dense(32, activation="relu", name="attrition_hidden")(shared2)

# Create the output layer
attrition_output = Dense(2, activation="softmax", name="attrition_output")(attrition_hidden)

In [72]:
# Create the model
model = Model(inputs=input_layer, outputs=[dept_output, attrition_output])

# Compile the model
model.compile(
    optimizer="adam",
    loss={
        "department_output": "categorical_crossentropy",
        "attrition_output": "categorical_crossentropy"
    },
    metrics={
        "department_output": "accuracy",
        "attrition_output": "accuracy"
    }
)

# Summarize the model
model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)  │ (None, 10)        │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared1 (Dense)     │ (None, 64)        │        704 │ input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared2 (Dense)     │ (None, 128)       │      8,320 │ shared1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_hidden   │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_hidden    │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_output   │ (None, 3)         │         99 │ department_hidde… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_output    │ (None, 2)         │         66 │ attrition_hidden… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 17,445 (68.14 KB)

 Trainable params: 17,445 (68.14 KB)

 Non-trainable params: 0 (0.00 B)

In [74]:
# Train the model
history = model.fit(
    X_train_scaled,
    {
        "department_output": y_train_dept,
        "attrition_output": y_train_attr
    },
    epochs=100,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.9872 - attrition_output_loss: 0.0525 - department_output_accuracy: 0.9180 - department_output_loss: 0.2448 - loss: 0.2972 - val_attrition_output_accuracy: 0.7585 - val_attrition_output_loss: 1.0960 - val_department_output_accuracy: 0.6144 - val_department_output_loss: 1.2233 - val_loss: 2.3919
Epoch 2/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.9883 - attrition_output_loss: 0.0617 - department_output_accuracy: 0.9155 - department_output_loss: 0.2380 - loss: 0.2996 - val_attrition_output_accuracy: 0.7458 - val_attrition_output_loss: 1.1909 - val_department_output_accuracy: 0.6144 - val_department_output_loss: 1.2626 - val_loss: 2.5353
Epoch 3/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9926 - attrition_output_loss: 0.0471 - department_output_accuracy: 0.9402 - department_output_loss: 0.2081 - loss: 0.2553 - val_attrition_output_accuracy: 0.7542 - 

In [75]:
# Evaluate the model with the testing data
eval_results = model.evaluate(
    X_test_scaled,
    {
        "department_output": y_test_dept,
        "attrition_output": y_test_attr
    },
    verbose=1
)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - attrition_output_accuracy: 0.7488 - attrition_output_loss: 2.1155 - department_output_accuracy: 0.5284 - department_output_loss: 3.8339 - loss: 5.9942


In [78]:
# Print the accuracy for both department and attrition
print(f"Department predictions accuracy: {eval_results[3]}")
print(f"Attrition predictions accuracy: {eval_results[4]}")

Department predictions accuracy: 0.7925170063972473
Attrition predictions accuracy: 0.5782312750816345


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy is a useful starting point, but it may not be the best performing metric depending on class imbalance. For example, if most employees do not leave the company, a model could achieve high accuracy by using "No Attrition." In such cases, precision, recall, or F1-score might better reflect performance, especially for attrition prediction where false negatives could impact the results. The department class is also imbalanced so it might benefit from not using accuracy as well.
2. I used the softmax activation function for both output layers. Softmax is appropriate for multi-class classification problems where the outputs are one-hot encoded. For attrition, although it's a binary outcome, the labels were one-hot encoded, so softmax with two output neurons was the appropriate choice. For department prediction, softmax is ideal as it handles three mutually exclusive classes.
3.
*  Add regularization (dropout or L2) to reduce overfitting.
*   Use early stopping or learning rate scheduling to optimize training duration.
*   Try different model architectures (e.g., deeper or wider layers, or recurrent layers if data is temporal).
*   Balance the dataset using oversampling (e.g., SMOTE) if class imbalance is significant.
*   Tune hyperparameters such as batch size, learning rate, or number of neurons using grid search or random search.





